version: "3.9"
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 20s ; python ./app.py"
    depends_on:
      - mysql
    ports:
      - 5001:5000 

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - "3306:3306"
    expose:
      - "3306"

  proxy:
    depends_on:
      - pythonapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    build: ./nginx/
    restart: unless-stopped
    ports:
      - 80:80
    image: nginx:latest