version: "3.9"
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 20s ; python ./app.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - "3306:3306"
    expose:
      - "3306"