version: "3.9"
services:
  db:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: mydb
      MYSQL_USER: newuser
      MYSQL_PASSWORD: "777"
    expose:
      - "3306"
  python_service:
    image: "python:3.7-alpine"
    volumes:
      - "./app.py:/code/app.py"
    links:
      - db