version: "3.9"
services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: '123'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
      - "./mysql/db_volume:/var/lib/mysql"
    expose:
      - "3306"
    networks:
      - backend

  pythonapp:
    build: ./python/
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - backend
      - frontend 

  proxy:
    depends_on:
      - pythonapp
    build: ./nginx/
    restart: unless-stopped
    ports:
      - 60:60
    image: nginx:latest
    networks:
      - frontend

networks:
  backend:
  frontend:
  



