FROM python:latest

WORKDIR /usr/app/src

COPY requirements.txt ./

RUN pip install -r ./requirements.txt

ENV FLASK_APP app.py
ENV FLASK_RUN_PORT 8000
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 8000

COPY movies.csv links.csv ratings.csv tags.csv RTmovies.csv ./

COPY app.py ./

WORKDIR /usr/app/src/templates

COPY view_data.html view_ratings.html view_links.html view_tags.html index.html result.html search.html ./

WORKDIR /usr/app/src

CMD ["flask", "run"]