FROM python:latest

WORKDIR /usr/app/src

COPY requirements.txt ./

RUN pip install -r ./requirements.txt

ENV FLASK_APP app.py
ENV FLASK_RUN_PORT 8000
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 8000

COPY movies.csv links.csv ratings.csv tags.csv RTmovies.csv ./

COPY app.py ./

COPY styles.css ./

WORKDIR /usr/app/src/templates

COPY templates/base.html templates/index.html templates/view_data.html templates/view_ratings.html templates/view_links.html templates/view_tags.html templates/result.html templates/search.html ./

WORKDIR /usr/app/src

CMD ["flask", "run"]